### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by juantascon** [strash/everybody-wants-that-line.nvim#2]
**Prerequisites**
- [v0.7.0] neovim version =
- [yes] I'm using LSP = (select one - yes/no)
- [3] [laststatus](https://neovim.io/doc/user/options.html#'laststatus') = (select one - 0, 1, 2, 3)

**Describe the bug**

I'm getting this error when running that-line:

```failed to load strash/everybody-wants-that-line.nvim; reason: ...-that-line.nvim/lua/everybody-wants-that-line/colors.lua:15: Invalid highlight name: diffAdded```

**To Reproduce**
1. install current main: 6b3542183485e8c35209d89f8c6d2ee5bc0f011c
2. run:       require("everybody-wants-that-line").setup({})

**Expected behavior**
the plugin doesn't crash

**Comment by strash** [comment]
Hey @juantascon what colorscheme are you using?
