### ISSUE TITLE
Breaks when in dirbuf.nvim buffer

### ISSUE THREAD

**Issue by sahilsehwag** [strash/everybody-wants-that-line.nvim#6]
**Prerequisites**
- neovim version = 0.8
- I'm using LSP = yes
- [laststatus](https://neovim.io/doc/user/options.html#'laststatus') = 2
- colorscheme = projekt0n/github-nvim-theme

**Describe the bug**
Breaks when in "elihunter173/dirbuf.nvim" buffer
`Invalid expression: v:lua.require('everybody-wants-that-line')._set_statusline()`

**To Reproduce**
Open dirbuf.nvim buffer

**Expected behavior**

**Screenshots**
<img width="1041" alt="Screenshot 2023-01-10 at 1 36 05 PM" src="https://user-images.githubusercontent.com/10343213/211495441-b6e60d4e-6c39-4184-be03-b65c96812a37.png">

**Additional context**

**Comment by strash** [comment]
Hi @sahilsehwag, if you have time, please test the fix on "develop" branch.

**Comment by strash** [comment]
Merged to main anyway. 😄
