### ISSUE TITLE
Setting to disable current file's path

### ISSUE THREAD

**Issue by sahilsehwag** [strash/everybody-wants-that-line.nvim#7]
**Is your feature request related to a problem? Please describe.**
Setting to disable filepath component in statusline

**Describe the solution you'd like**
When using winbar to show filepath, its redundant to show in statusline. Ideally every statusline component should have option to enable/disable to suit each user's usecase

**Describe alternatives you've considered**

**Additional context**

**Comment by strash** [comment]
Now you can enable or disable each component.
