### ISSUE TITLE
Ability to make statusline background transparent

### ISSUE THREAD

**Issue by sahilsehwag** [strash/everybody-wants-that-line.nvim#8]
**Is your feature request related to a problem? Please describe.**
Ability to make statusline background transparent

**Describe the solution you'd like**

**Describe alternatives you've considered**
 Unable to make it work with [nvim-transparent](https://github.com/xiyaowong/nvim-transparent)

**Additional context**

**Comment by strash** [comment]
Hi, you can do something like this if you use packer:
```lua
use({
	"xiyaowong/nvim-transparent",
	-- ensure this plugin is loaded after the statusline plugin
	after = "everybody-wants-that-line.nvim",
	config = function()
		local extra_groups = {
			"StatusLine",
			"StatusLineNC",
		}
		for _, value in pairs(require("everybody-wants-that-line.colors").group_names) do
			table.insert(extra_groups, value)
		end
		require("transparent").setup({
			extra_groups = extra_groups
		})
	end
})

```
